{% set name = "rplibs" %}
{% set version = "6.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rplibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2df6ed74b9a57a1a44a46de52d689fc967046a56e18a85e16f89fbb511216df8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - networkx >=2.5
    - brs_utils >=1.26.0
    - filetype
    - chemlite >=2.9.0
    - rr_cache
    - cobra
    - libsbml

test:
  imports:
    - rplibs

about:
  home: https://github.com/brsynth/rplibs/tree/main
  summary: "Defines an enriched SBML structure with additional fields relative to RetroPath2 objects."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - ramez17khaled
    - breakthewall
